name: Glitter Tower
favicon: null
layout_spectrum: 0.9272888584528118
typography_spectrum: 0.19785270560532808
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.48862562235444784
  lightness: 0.5525778273586184
  saturation: 0.18441215809434652
  rhythmicContrast: 0.7403390954714268
purpose: []
